# Generated by Django 5.0.6 on 2024-05-19 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ratingg',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'Принимается только положительные числа и ноль')]),
        ),
    ]
