# Generated by Django 5.0.4 on 2024-05-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(255)])),
                ('author', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(255)])),
                ('label', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(255)])),
                ('producer', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(255)])),
                ('genre', models.CharField(choices=[('rock', 'Рок'), ('rap', 'Рэп'), ('hiphop', 'Хипхоп'), ('classical', 'Классика'), ('jazz', 'Джаз'), ('metal', 'Метал'), ('folk', 'Фолк'), ('pop', 'Поп'), ('raggy', 'Рэгги'), ('bluze', 'Блюз'), ('other', 'Другое')], max_length=10)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
    ]
