# Generated by Django 5.0.6 on 2024-05-19 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='label',
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'Принимается только положительные числа и ноль')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'Длина должна быть более 4 символов.')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('rock', 'Рок'), ('rap', 'Рэп'), ('classical', 'Классика'), ('jazz', 'Джаз'), ('metal', 'Метал'), ('pop', 'Поп'), ('other', 'Другое')], max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'Длина должна быть более 4 символов.')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='producer',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, 'Длина должна быть более 4 символов.')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1890, 'Не раньше 1890 года.'), django.core.validators.MaxValueValidator(2025, 'Не позже 2025 года')]),
        ),
    ]
